### PR TITLE
152-swiffyslider

### PR DESCRIPTION
**Pull request by nicped**
Adding Swiffy Slider and Carousel to vanilla list

### CODE REVIEW

**Comment by TixieBorg** [comment]
Hi, thanks for the submit! 

I have a few questions before going furthermore through the PR:

1. Knowing the thumbnail won't stay animated: do you wanna keep it this one?
2. The current thumb doesn't match the 308x195 ratio so hide some interesting part of the plugin's UI (navigation buttons for example). No biggie but same question than previous point.
3. Are you willing to replace all pictures of women in bikini used in every examples of your plugin by something else not objectifying? 

Best regards

**Comment by nicped** [comment]
Thank you for the review. I have updated the image in the pull request to follow the ratio.
Also updated the example site to not use the mentioned image.

**Comment by TixieBorg** [comment]
Merged!

I made some wording adaptions to optimize search and clarity of the benefits your plugin bring as well than avoiding get target as duplicated content by crawlers for having very similar text than your own website.

Thanks again for your contribution!

**Comment by nicped** [comment]
Thanks!

**Pull request merged**
